## 0) At the beginning of your Jupyter notebook, include the following code chunk. This will load required packages:¶

In [19]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

## 1)	Create an array containing 4 string elements: your first name, your last name, your birth state and your favorite color. 

In [20]:
my_array = make_array('Yann','Wollman','California','Blue')
my_array

array(['Yann', 'Wollman', 'California', 'Blue'], dtype='<U10')

### a.	Use a numpy function to make all elements uppercase. 

In [21]:
np.char.upper(my_array)

array(['YANN', 'WOLLMAN', 'CALIFORNIA', 'BLUE'], dtype='<U10')

### b.	Use a numpy function to count the number of times the letter “a” appears in each element of your array.

In [22]:
np.char.count(my_array, "a")

array([1, 1, 2, 0])

### c.	Optional: Use a numpy function to find the length of each element in the array. You may need to Google this. 

In [23]:
print([len(i) for i in my_array])

# Other method with numpy
my_array_length = np.vectorize(len)
print(my_array_length(my_array))

[4, 7, 10, 4]
[ 4  7 10  4]


## 2)	Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 45. 

In [24]:
new_array = np.arange(1, 46, 4)
new_array

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

### a.	Use numpy to find the sum and the product of the elements of this array.

In [25]:
sum_array = np.sum(new_array)
print(sum_array)

product_array = np.prod(new_array)
print(product_array)

276
616159193


### b.	Use numpy to take the natural log of each element.

In [26]:
Log = np.log(new_array)
Log

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

### c.	Optional: The numpy function np.diff finds the difference between adjacent elements of an array. Find the SUM of adjacent elements of this array. 



In [31]:
Sum = np.sum(np.diff(Log))
Sum

3.8066624897703196